# Task 2 Create database by Salem Solomon
drop database if exists league;
create database league;
use league;
show databases; 

# Task 3 Create Tables by Salem Solomon
SHOW TABLES;
CREATE TABLE SEASON_SS(
	SEASON_ID_SS INT PRIMARY KEY,
    REGISTRATION_START_SS DATE NOT NULL,
    REGISTRATION_END_SS DATE NOT NULL,
    SEASON_START_SS DATE NOT NULL,
    SEASON_END_SS DATE NOT NULL,
    FALL_SS VARCHAR(45),
    SPRING_SS VARCHAR(45),
    SUMMER_SS VARCHAR(45),
    WINTER_SS VARCHAR(45));
    
CREATE TABLE DIVISION_SS(
	DIVISION_ID_SS INT PRIMARY KEY,
    AGE_SS VARCHAR(25) NOT NULL,
    SEX_SS VARCHAR(10) NOT NULL,
    RANK_SS INT NOT NULL,
    DIVISION_EMAIL_SS VARCHAR(30) NOT NULL UNIQUE,
    DIVISION_PHONE_SS CHAR(12) NOT NULL UNIQUE,
    SEASON_ID_SS INT,
    FOREIGN KEY (SEASON_ID_SS) REFERENCES SEASON_SS(SEASON_ID_SS));

    
CREATE TABLE CLUB_SS(
	CLUB_ID_SS INT PRIMARY KEY,
    CLUB_NAME_SS VARCHAR(22) NOT NULL,
    CLUB_EMAIL_SS VARCHAR(30) NOT NULL UNIQUE,
    CLUB_PHONE_SS CHAR(12) NOT NULL UNIQUE,
    CLUB_ABBREV_SS VARCHAR(5) NOT NULL);
    
CREATE TABLE TEAM_SS(
    TEAM_ID_SS INT PRIMARY KEY,
    TEAM_NAME_SS VARCHAR(25) NOT NULL,
    PLAYER_BIRTH_YEAR_SS INT NOT NULL,
    PLAYER_GENDER_SS VARCHAR(10) NOT NULL,
    TEAM_EMAIL_SS VARCHAR(25) NOT NULL UNIQUE,
    DIVISION_ID_SS INT,
    FOREIGN KEY (DIVISION_ID_SS) REFERENCES DIVISION_SS(DIVISION_ID_SS));

CREATE TABLE ASSIGNMENT (
    CLUB_ID_SS INT,
    TEAM_ID_SS INT,
    FOREIGN KEY (CLUB_ID_SS) REFERENCES CLUB_SS (CLUB_ID_SS),
    FOREIGN KEY (TEAM_ID_SS) REFERENCES TEAM_SS (TEAM_ID_SS));
    
CREATE TABLE PLAYER_SS(
	PLAYER_ID_SS INT PRIMARY KEY,
	FIRST_NAME_SS VARCHAR(15) NOT NULL,
	LAST_NAME_SS VARCHAR(15) NOT NULL,
    DOB_SS DATE NOT NULL,
    JERSEY_NUMBER_SS CHAR(2) NOT NULL,
    PARENT_EMAIL_SS VARCHAR(20) NOT NULL,
    TEAM_ID_SS INT,
    FOREIGN KEY (TEAM_ID_SS) REFERENCES TEAM_SS(TEAM_ID_SS));
    
  CREATE TABLE COACH_SS(
	COACH_ID_SS INT PRIMARY KEY,
    COACH_FNAME_SS VARCHAR(15) NOT NULL,
    COACH_LNAME_SS VARCHAR(15) NOT NULL,
    COACH_DOB_SS DATE NOT NULL,
    START_YEAR_SS INT NOT NULL,
    COACH_PHONE_SS CHAR(12) NOT NULL UNIQUE);
    

SHOW TABLES;
DESCRIBE DIVISION_SS;
DESCRIBE SEASON_SS;
DESCRIBE CLUB_SS;
DESCRIBE TEAM_SS;
DESCRIBE PLAYER_SS;
DESCRIBE COACH_SS;


# TASK 4 ADD DATA BY SALEM SOLOMON
SELECT * FROM SEASON_SS;
SELECT *  FROM DIVISION_SS;
SELECT * FROM CLUB_SS;
SELECT * FROM PLAYER_SS;
SELECT * FROM COACH_SS;
INSERT INTO SEASON_SS 
(SEASON_ID_SS, REGISTRATION_START_SS, REGISTRATION_END_SS, SEASON_START_SS, SEASON_END_SS, FALL_SS, SPRING_SS, SUMMER_SS, WINTER_SS) 
VALUES 
(1, '2017-03-01', '2017-08-01','2017-09-21', '2017-12-21', 'Fall 2017', NULL, NULL, NULL),
(2, '2019-07-01', '2019-09-01', '2019-09-21', '2019-12-21', NULL, NULL, NULL, 'Winter 2019'),
(3, '2020-07-01', '2020-09-01', '2020-09-21', '2020-12-21', NULL, 'Spring 2019', NULL, NULL),
(4, '2022-07-01', '2022-09-01', '2022-09-21', '2022-12-21', NULL, null, NULL, NULL),
(5, '2023-07-01', '2023-09-01', '2023-09-21', '2023-12-21', NULL, 'Spring 2023', NULL, NULL);

INSERT INTO DIVISION_SS (DIVISION_ID_SS, AGE_SS,SEX_SS, RANK_SS, DIVISION_EMAIL_SS, DIVISION_PHONE_SS, SEASON_ID_SS)
VALUES 
  (1, 'Under 13','female',2,'abc@gmail.com','555-666-7777', 1),
  (2, 'Under 13','male',2,'number2@gmail.com','553-646-7747', 1),
  (3, 'Over 13','male', 3, 'number3@gmail.com', '532-226-1177', 1),
  (4, 'Over 13','female', 1,'number4@gmail.com', '112-633-7123', 1),
  (5, 'Under 13', 'female', 1,'number5@gmail.com', '525-166-2345', 2),
  (6, 'Under 13', 'male', 1,'number6@gmail.com', '522-636-7717', 2),
  (7, 'Over 13', 'female', 1, 'number7@gmail.com', '324-616-3327', 2);
  
INSERT INTO CLUB_SS (CLUB_ID_SS, CLUB_NAME_SS, CLUB_EMAIL_SS, CLUB_PHONE_SS, CLUB_ABBREV_SS)
VALUES
(1, 'Falcons', 'falcons@gmail.com', '444-443-5678', 'FA'),
(2, 'Eagles', 'eagles@gmail.com', '423-223-7890', 'EA'),
(3, 'Dragons', 'dragons@gmail.com', '571-455-7865', 'DA'),
(4, 'Bulls', 'bulls@gmail.com', '877-241-0090', 'BA'),
(5, 'Seahawks', 'seahawks@gmail.com', '800-645-0987', 'SA');

INSERT INTO TEAM_SS (TEAM_ID_SS, TEAM_NAME_SS, PLAYER_BIRTH_YEAR_SS, PLAYER_GENDER_SS, TEAM_EMAIL_SS, DIVISION_ID_SS)
VALUES
(1, 'Green', 2009, 'female','green@gmail.com', 1),
(2, 'Red', 2003, 'female','red@gmail.com', 2),
(3, 'Blue', 2012, 'female','blue@gmai.com', 3),
(4, 'Orange', 2011, 'male', 'orange@gmail.com', 1),
(5, 'Yellow', 2009, 'female','yellow@gmail.com', NULL);

INSERT INTO PLAYER_SS VALUES 
(560, 'ROBERT', 'GARCIA', '1982-09-12', '35', 'MELLY@GMAIL.COM', 1),
(561, 'DELTA', 'BOWMAN', '1980-02-11', '35', 'SANDY@GMAIL.COM', 3),
(562, 'SANDRA', 'KESTON', '1972-05-17', '20', 'FERNANDEZ@GMAIL.COM', 2),
(563, 'MICHAEL', 'KWART', '1990-10-12', '21', 'BOWMAN@GMAIL.COM', 4),
(564, 'PAMELA', 'KEATON', '1975-08-10', '17', 'MATHERS@GMAIL.COM', 5);

INSERT INTO COACH_SS VALUES
(350, 'JOHN', 'BEKELE', '1972-02-03', '2020', '571-445-9980'),
(351, 'SEBAH', 'KHIAR', '1986-09-09', '2020', '556-990-8978'),
(352, 'LIDIYA', 'MUSSE', '1974-03-10', '2017', '334-675-7687'),
(353, 'ALLYSA', 'ASSEFA', '1973-10-04', '2015', '443-543-2345'),
(354, 'MELODIA', 'PEMBROOKE', '1977-03-09', '2014', '703-009-8912');


# Task 5 Query the Data by Salem Solomon
# Query 1
	#SELECT TEAM_NAME_SS AS name, TEAM_EMAIL_SS AS email
	#FROM TEAM_SS
	#JOIN SEASON_TEAM_SS ON TEAM_SS.TEAM_ID_SS = SEASON_TEAM_SS.TEAM_ID_SS
	#JOIN SEASON_SS ON SEASON_TEAM_SS.SEASON_ID_SS = SEASON_SS.SEASON_ID_SS
	#ORDER BY TEAM_NAME_SS ASC;
 # QUERY 2
	#SELECT DIVISION_PHONE_SS AS "Division Phone", SEASON_ID_SS AS "Season", DIVISION_NAME_SS AS "Division Name"
	#FROM DIVISION
	#JOIN TEAM ON TEAM.DIVISION_ID_SS = DIVISION.DIVISION_ID_SS
	#WHERE TEAM.TEAM_NAME_SS = 'Red'
	#ORDER BY SEASON_SS;

# query 3
	#SELECT TEAM_NAME_SS AS "TEAM NAME", AGE_SS AS "PLAYER AGE", RANK_SS AS "PLAYER RANK"
	#FROM CLUB 
	#JOIN DIVISION ON DIVISION.CLUB_ID_SS = CLUB.CLUB_ID_SS
	#JOIN TEAM ON TEAM.DIVISION_ID_SS = DIVISION.DIVISION_ID_SS
	#WHERE CLUB_NAME_SS = 'EAGLES';
#QUERY 4
	#SELECT TEAM.TEAM_NAME_SS AS "TEAM NAME", CLUB.CLUB_NAME_SS AS "CLUB NAME", PLAYER.DOB_SS AS "DATE OF BIRTH"
	#FROM CLUB_SS
	#JOIN TEAM_SS ON CLUB.CLUB_ID_SS = TEAM.CLUB_ID_SS
	#JOIN PLAYER_SS ON TEAM.TEAM_ID_SS = PLAYER.TEAM_ID_SS
	#WHERE TEAM.SPRING = '2019' AND PLAYER.AGE_SS <= 12;
# QUERY 1
	#SELECT COUNT(LAST_NAME_SS) 
	#FROM PLAYER_SS
    #WHERE SEASON_SS = 'FALL 2020';
# Query 2
	#SELECT COUNT (COACH_LNAME_SS)
    #FROM COACH_SS
    #WHERE SEASON_SS = 'SPRING 2020';
#QUERY 3
	# SELECT CONCAT( FIRST_NAME_SS, LAST_NAME_SS) AS PLAYER
    # FROM PLAYER_SS
    # WHERE JERSEY_NUMBER_SS =(SELECT MAX(JERSEY_NUMBER_SS) FROM PLAYER);
#QUERY 4
	# SELECT CONCAT(COACH_FNAME_SS, ' ', COACH_LNAME_SS) AS 'COACH'
    # FROM COACH_SS
    #WHERE START_YEAR_SS =(SELECT MIN(START_YEAR_SS) FROM COACH_SS;

















  



   
    
    